### ISSUE TITLE
Can you share how you've created chart of same percentaged colors

### ISSUE THREAD

**Issue by neelkadia-zz** [cyrilis/colors-palette#2]

**Comment by cyrilis** [comment]
@neelkadia It's quite easy as only you've got the color datas 😉 

Check out:
https://codepen.io/cyrilis/pen/VWxZww

**Comment by neelkadia-zz** [comment]
Wonderful! Thanks much!

**Comment by cyrilis** [comment]
@neelkadia You're welcome, will close it.
